var emaillogin = document.getElementById('inputlogin')
var senhalogin = document.getElementById('inputsenha')
var botãologin = document.getElementById('loginbotão') 
var errologin = document.getElementById('erroemail')
var lembrar = document.getElementById('lembrarradio')